syntax = "proto3";

package post;

option java_package = "com.postservice";
option java_multiple_files = true;

service PostService {
  rpc getPostsByUserIds (UserIdsRequest) returns (PostListResponse);

  // New LikePost RPC
  rpc likePost (LikePostRequest) returns (LikePostResponse);

  rpc savePost(SavePostRequest) returns (SavePostResponse);
  rpc getSavedPosts(GetSavedPostsRequest) returns (GetSavedPostsResponse);

  rpc IsPostLikedByUser(IsPostLikedByUserRequest) returns (IsPostLikedByUserResponse);
  rpc IsPostSavedByUser(IsPostSavedByUserRequest) returns (IsPostSavedByUserResponse);
  rpc GetLikeCount(GetLikeCountRequest) returns (GetLikeCountResponse);
  rpc GetPostById(PostIdRequest) returns (PostMessage);
}

message UserIdsRequest {
  repeated string userIds = 1; // UUIDs as strings
}

message PostMessage {
  string id = 1;
  string userId = 2;
  string userName = 3;
  string profilePic = 4;
  string content = 5;
  repeated string imageUrls = 6;
  string createdAt = 7;
  int32 likeCount = 8;
  int32 commentCount = 9;
  int32 shareCount = 10;
  bool isRepost = 11;
  optional string repostedAt = 12;
  string repostedBy = 13;
  optional string originalPostId = 14;

}

// NEW: LikePostRequest message
message LikePostRequest {
  string postId = 1;
  string userId = 2; // The user who is liking the post
}

// NEW: LikePostResponse message
message LikePostResponse {
  bool liked = 1;
  int32 likeCount = 2;
}

message PostListResponse {
  repeated PostMessage posts = 1;
}


// Save/Unsave request
message SavePostRequest {
  string postId = 1;
  string userId = 2;
}

// SavePostResponse
message SavePostResponse {
  bool saved = 1;         // true if now saved, false if unsaved
  string message = 2;     // optional response message
}

// Fetch Saved Posts
message GetSavedPostsRequest {
  string userId = 1;
}

message GetSavedPostsResponse {
  repeated PostMessage posts = 1;
}

message IsPostLikedByUserRequest {
  string postId = 1;
  string userId = 2;
}

message IsPostLikedByUserResponse {
  bool liked = 1;
}

message IsPostSavedByUserRequest {
  string postId = 1;
  string userId = 2;
}

message IsPostSavedByUserResponse {
  bool saved = 1;
}

message GetLikeCountRequest {
  string postId = 1;
}

message GetLikeCountResponse {
  int32 likeCount = 1;
}

message PostIdRequest {
  string postId = 1;
}