spring:
  application:
    name: notification-service

  kafka:
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest
    listener:
      concurrency: 1

server:
  port: 4054

logging:
  level:
    com:
      fc:
        notificationservice: DEBUG

grpc:
  server:
    port: 6562
