spring:
  kafka:
    bootstrap-servers: localhost:9092

  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/notifications-db?authSource=admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: false
    hostname: localhost
