spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:4000
              - http://localhost:5173
              - http://localhost:4012
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: auth-service-route
#          uri: http://auth-service:4051
#          uri: http://localhost:4051
          uri: lb://auth-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: post-service-route
#          uri: http://post-service:4050
#          uri: http://localhost:4050
          uri: lb://post-service
          predicates:
            - Path=/api/post/**
          filters:
            - StripPrefix=2
            - JwtValidation
          # Route for /api/story/** to stories-service
        - id: story-service-route
#          uri: http://stories-service:4053
#          uri: http://localhost:4053
          uri: lb://stories-service
          predicates:
            - Path=/api/stories/**
          filters:
                - StripPrefix=2
                - JwtValidation

        - id: chat-service-route
#          uri: http://chat-service:4052
#          uri: http://localhost:4052
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**, /api/presence/**, /api/reactions/**
          filters:
            - JwtValidation
            - RewritePath=/api/chat/(?<segment>.*), /$\{segment}
#            - name: JwtValidation
#              args:
#                - excludedPaths: /chat-ws/**
        - id: notification-service-route
#          uri: http://notification-service:4054
#          uri: http://localhost:4054
          uri: lb://notification-service
          predicates:
              - Path=/api/notifications/**
          filters:
              - StripPrefix=2
              - JwtValidation
        - id: feed-service-route
#          uri: http://localhost:4055
          uri: lb://feed-service
          predicates:
            - Path=/api/feed/**
          filters:
            - StripPrefix=2
            - JwtValidation
        - id: api-docs-users-route
#          uri: http://auth-service:4051
#          uri: http://localhost:4051
          uri: lb://auth-service
          predicates:
            - Path=/api-docs/users
          filters:
            - RewritePath=/api-docs/users,/v3/api-docs

        - id: api-docs-post-route
#          uri: http://post-service:4050
#          uri: http://localhost:4050
          uri: lb://post-service
          predicates:
            - Path=/api-docs/post
          filters:
            - RewritePath=/api-docs/post,/v3/api-docs

        - id: api-docs-stories-route
          uri: lb://stories-service
          predicates:
            - Path=/api-docs/stories
          filters:
            - RewritePath=/api-docs/stories,/v3/api-docs

        - id: api-docs-chat-route
          uri: lb://chat-service
          predicates:
             - Path=/api-docs/chat
          filters:
             - RewritePath=/api-docs/chat,/v3/api-docs

        - id: api-docs-notification-route
          uri: lb://notification-service
          predicates:
            - Path=/api-docs/notification
          filters:
            - RewritePath=/api-docs/notification,/v3/api-docs

        - id: api-docs-feed-route
          uri: lb://feed-service
          predicates:
            - Path=/api-docs/feed
          filters:
            - RewritePath=/api-docs/feed,/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /api-docs/users
      - name: Post Service
        url: /api-docs/post
      - name: Stories Service
        url: /api-docs/stories
      - name: Chat Service
        url: /api-docs/chat
      - name: Notification Service
        url: /api-docs/notification
      - name: Feed Service
        url: /api-docs/feed

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: false
    hostname: localhost

server:
  port: 4004

#auth:
#  service:
#    url: http://auth-service:4051
#     url: http://localhost:4051

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
