spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:4000
              - http://localhost:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: auth-service-route
#          uri: http://auth-service:4051
          uri: http://localhost:4051
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: post-service-route
#          uri: http://post-service:4050
          uri: http://localhost:4050
          predicates:
            - Path=/api/post/**
          filters:
            - StripPrefix=2
            - JwtValidation
          # Route for /api/story/** to stories-service
        - id: story-service-route
#          uri: http://stories-service:4053
          uri: http://localhost:4053
          predicates:
            - Path=/api/stories/**
          filters:
                - StripPrefix=2
                - JwtValidation

        - id: chat-service-route
#          uri: http://chat-service:4052
          uri: http://localhost:4052
          predicates:
            - Path=/api/chat/**, /api/presence/**, /api/reactions/**
          filters:
            - JwtValidation
            - RewritePath=/api/chat/(?<segment>.*), /$\{segment}
#            - name: JwtValidation
#              args:
#                - excludedPaths: /chat-ws/**
        - id: notification-service-route
#          uri: http://notification-service:4054
          uri: http://localhost:4054
          predicates:
              - Path=/api/notifications/**
          filters:
              - StripPrefix=2
              - JwtValidation
        - id: feed-service-route
          uri: http://localhost:4055
          predicates:
            - Path=/api/feed/**
          filters:
            - StripPrefix=2
            - JwtValidation
        - id: api-docs-users-route
#          uri: http://auth-service:4051
          uri: http://localhost:4051
          predicates:
            - Path=/api-docs/users
          filters:
            - RewritePath=/api-docs/users,/v3/api-docs

        - id: api-docs-post-route
#          uri: http://post-service:4050
          uri: http://localhost:4050
          predicates:
            - Path=/api-docs/post
          filters:
            - RewritePath=/api-docs/post,/v3/api-docs

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka-server:8761/eureka
#  instance:
#    prefer-ip-address: true

server:
  port: 4004

auth:
  service:
#    url: http://auth-service:4051
     url: http://localhost:4051

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
