spring:
  application:
    name: post-service

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false          # prod default; dev will override
    properties:
      hibernate:
        format_sql: false

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: all
      retries: 3

server:
  port: 4050

jwt:
  secret: DnFG/tvGjFAfDRZvu2+qZbEQ+SSjLRsNhoXOrtYkTfw=

logging:
  level:
    root: INFO
    org.springframework.kafka: INFO

grpc:
  server:
    port: 9099
  client:
    auth-service:
      address: discovery:///auth-service
      negotiation-type: plaintext
      enable-keep-alive: true
      default-load-balancing-policy: round_robin

resilience4j:
  circuitbreaker:
    instances:
      aiService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  timelimiter:
    instances:
      aiService:
        timeoutDuration: 3s

